import prog.util.PistonPowerModel;
import prog.util.PistonPowerModel.CompressorStageParams;

/** Generates common JVM/JS regression vectors using the unchanged legacy Java model.
 * Compile this with src/prog/util/{PhysicsConstants,AtmosphereModel,PowerCurveHelper,
 * PistonPowerModel,Logger}.java, then redirect stdout to LegacyPistonReference.kt.
 */
public class GenerateKotlinPowerReference {
    public static void main(String[] args) throws Exception {
        String[] fields = {"critAlt", "critPower", "deckPower", "deckAlt", "curvature", "wepCritAlt",
            "wepPowerMult", "speedManifoldMult", "constRpmAlt", "constRpmPower", "ceilingAlt",
            "ceilingPower", "oldAltitude", "oldPower", "oldPowerNewRpm", "wepDeckAlt",
            "wepConstRpmAlt", "stage0DeckAlt", "exactAltitudes"};
        CompressorStageParams[] stages = new CompressorStageParams[12];
        System.out.println("package voidmei.fm\n\n// Generated by test/GenerateKotlinPowerReference.java; synthetic parameters, not game validation.\ninternal object LegacyPistonReference {\n    val stages = listOf(");
        for (int i = 0; i < stages.length; i++) {
            CompressorStageParams p = new CompressorStageParams(4000, 1400, 1200, 3000, 1.2, 0.8, i);
            p.oldAltitude = 4000; p.oldPower = 1400; p.oldPowerNewRpm = 1400;
            if (i == 1 || i == 5) { p.constRpmAlt = 1800; p.constRpmPower = 1320; p.wepConstRpmAlt = 1000; p.curvature = 1.4; }
            if (i == 2 || i == 3 || i == 4 || i == 6 || i == 11) { p.ceilingAlt = 9000; p.ceilingPower = 600; }
            if (i == 3 || i == 11) { p.constRpmAlt = p.critAlt; p.constRpmPower = p.critPower; p.curvature = 1.6; }
            if (i == 4 || i == 5 || i == 11) { p.exactAltitudes = true; p.oldAltitude = 4500; p.oldPower = 1450; p.oldPowerNewRpm = 1500; p.wepDeckAlt = -500; }
            if (i == 6) { p.critAlt = 0; p.oldAltitude = 0; p.wepCritAlt = -500; p.deckPower = 1400; }
            if (i == 7) { p.constRpmAlt = -100; p.constRpmPower = 1150; p.wepConstRpmAlt = -500; }
            if (i == 8) { p.wepCritAlt = 5000; }
            if (i == 9) { p.wepCritAlt = 3750.4; p.oldAltitude = 4500.4; }
            if (i == 10) { p.wepCritAlt = p.critAlt; p.wepPowerMult = 1; }
            stages[i] = p;
            System.out.println("        CompressorStage(");
            for (String f : fields) System.out.println("            " + f + " = " + CompressorStageParams.class.getField(f).get(p) + ",");
            System.out.println("        ),");
        }
        System.out.println("    )\n    val peaks = listOf(");
        for (CompressorStageParams stage : stages) {
            System.out.println("        " + PistonPowerModel.peakWepPower(new CompressorStageParams[] {stage}) + ",");
        }
        System.out.println("    )\n    val samples = \"\"\"");
        double[] alts = {-500, 0, 999, 1800, 2999, 3000, 3750.45, 4000, 4500, 4500.5, 5000, 7000, 9000, 10000};
        for (int stage = 0; stage < stages.length; stage++) {
            for (int condition = 0; condition < 4; condition++) {
                boolean wep = (condition & 1) != 0;
                double speed = condition < 2 ? 0 : 450;
                boolean eas = condition == 3;
                for (double alt : alts) {
                    double power = PistonPowerModel.powerAtAltitudeAdvanced(stages[stage], alt, wep, speed, eas, 15);
                    System.out.println(stage + "," + alt + "," + wep + "," + speed + "," + eas + "," + power);
                }
            }
        }
        System.out.println("\"\"\".trimIndent()\n}");
    }
}
