import parser.Blkx;
import prog.util.FMPowerExtractor;
import prog.util.PistonPowerModel.CompressorStageParams;
import prog.util.Logger;

/** Compile against the unchanged legacy sources and dep/*.jar; emits shared Kotlin reference data. */
public class GenerateKotlinPipelineReference {
    public static void main(String[] args) throws Exception {
        Logger.setMinLevel(Logger.Level.ERROR);
        String[] fields = {"critAlt", "critPower", "deckPower", "deckAlt", "curvature", "wepCritAlt",
            "wepPowerMult", "speedManifoldMult", "constRpmAlt", "constRpmPower", "ceilingAlt",
            "ceilingPower", "oldAltitude", "oldPower", "oldPowerNewRpm", "wepDeckAlt", "wepConstRpmAlt", "stage0DeckAlt"};
        System.out.println("package voidmei.fm\n\n// Generated by test/GenerateKotlinPipelineReference.java using the unchanged legacy extractor.\ninternal val legacyPipelineSamples = \"\"\"");
        for (int scenario = 0; scenario < 8; scenario++) {
            Blkx b = new Blkx("/voidmei-nonexistent-reference-input", "reference", false);
            b.compNumSteps = 2;
            b.compAlt = new double[]{4000, 6500}; b.compPower = new double[]{1400, 1600};
            b.compCeil = new double[]{9000, 10000}; b.compCeilPwr = new double[]{600, 700};
            b.compConstRpmAlt = new double[]{1800, 3000}; b.compConstRpmPower = new double[]{1300, 1450};
            b.compBoost = new double[]{0, 1.02}; b.hasCompBoost = new boolean[]{false, true};
            b.compRpmRatio = new double[]{1.3, 1.5}; b.speedToManifoldMultiplier = 0.8;
            b.militaryRPM = 2400; b.wepRPM = 2700; b.shaftRPMMax = scenario == 0 || scenario >= 6 ? 0 : 2700;
            b.rpmNom = scenario == 6 ? 2600 : 0; b.governorMaxParam = scenario == 7 ? 2500 : 0;
            b.compPressureAtRPM0 = 0.3; b.compOmegaFactorSq = 1; b.hasCompOmegaFactorSq = true;
            b.explicitExactAltitudes = scenario == 2;
            b.militaryMP = 1.4; b.compAfterburnerPressureBoost = new double[]{1.05, 1};
            b.throttleBoost = 1.05; b.octaneAfterburnerMult = 1.1; b.wepManifoldPressure = 1.7;
            b.deckPower = 1200; b.aftbCoff = 1.2;
            Blkx.FuelModification fuel = null;
            if (scenario == 3) {
                fuel = new Blkx.FuelModification(); fuel.type = Blkx.FuelModification.FuelType.SOVIET_B100;
                fuel.sovietOctaneHpBonus = 50;
            } else if (scenario == 4 || scenario == 5) {
                fuel = new Blkx.FuelModification(); fuel.type = Blkx.FuelModification.FuelType.BRITISH_150_OCTANE;
                fuel.britishAfterburnerMult = 1.5; fuel.britishAfterburnerCompressorMult = 1.2;
                fuel.britishInvertLogic = scenario == 5;
            }
            CompressorStageParams[] stages = FMPowerExtractor.extractStages(b, fuel);
            for (int i = 0; i < stages.length; i++) {
                StringBuilder row = new StringBuilder(scenario + "," + i);
                for (String field : fields) row.append(',').append(CompressorStageParams.class.getField(field).getDouble(stages[i]));
                System.out.println(row);
            }
        }
        System.out.println("\"\"\".trimIndent()");
    }
}
