package voidmei.config

/** Reading layout only; retain connection, recording, placement and window behaviour. */
fun AppSettings.withHudLayout(source: AppSettings): AppSettings = copy(
    hudAltitudeMode = source.hudAltitudeMode,
    hudNumberFont = source.hudNumberFont,
    hudLabelColor = source.hudLabelColor,
    hudValueColor = source.hudValueColor,
    hudWarningColor = source.hudWarningColor,
    hudUnitColor = source.hudUnitColor,
    hudShadeColor = source.hudShadeColor,
    hudFields = source.hudFields,
    hudCrosshair = source.hudCrosshair,
    hudCrosshairSizeDp = source.hudCrosshairSizeDp,
    hudCrosshairImage = source.hudCrosshairImage,
    hudCrosshairStretch = source.hudCrosshairStretch,
    hudCrosshairRight = source.hudCrosshairRight,
    hudHiddenLabels = source.hudHiddenLabels,
    hudAttitude = source.hudAttitude,
    hudAttitudeEarthFixed = source.hudAttitudeEarthFixed,
    hudAttitudeAoaLimits = source.hudAttitudeAoaLimits,
    hudCompassHeadingUp = source.hudCompassHeadingUp,
    hudMechanization = source.hudMechanization,
    hudAoaBarWarningPercent = source.hudAoaBarWarningPercent,
    hudAoaWarningPercent = source.hudAoaWarningPercent,
    hudGear = source.hudGear,
    hudFlaps = source.hudFlaps,
    hudFlapBar = source.hudFlapBar,
    hudAirbrake = source.hudAirbrake,
    hudFontScale = source.hudFontScale,
    hudEngineIndex = source.hudEngineIndex,
    hudEngineFields = source.hudEngineFields,
    hudWidthDp = source.hudWidthDp,
    hudReadingColumns = source.hudReadingColumns,
)
